apiVersion: v1
kind: Secret
metadata:
  name: acquisitions-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neondb_owner:npg_GS3XjQDVMUv1@ep-purple-boat-a1p7uiii-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  JWT_SECRET: "dev-jwt-secret-change-in-production-12345"
  ARCJET_KEY: "ajkey_01kksby45hf78tnhpzyhnqqp23"
  NODE_ENV: "production"
  ARCJET_ENV: "development"
